var niclang = {'EditHTML':'Edit HTML',
	               'bold':'Click to Bold',
	             'italic':'Click to Italic',
	          'underline':'Click to Underline',
	               'left': 'Left Align',
	             'center':'Center Align',
	              'right': 'Right Align',
	           'justify' :'Justify Align',
	                'ol' :'Insert Ordered List',
	                 'ul':'Insert Unordered List',
	'subscript':'Click to Subscript',
'superscript':' Click to Superscript',
	'strikethrough':'Click to Strike Through',
	'removeformat':'Remove Formatting', 
	 'indent':'Indent Text',
	'outdent':'Remove Indent',
	'outdent':'Horizontal Rule',
	'fontSize':'Select Font Size',
	'fontFamily':'Select Font Family',
	'fontFormat':'Select Font Format',
	'link':'Add Link',
	'unlink':'Remove Link',
	'editlink':'Add/Edit Link',
	'editopen' :'Open In',
	'benck':'Current Window'',
	'neck':'New Window',
  'paslink':'You must enter a URL to Create a Link',
		'foncolor':'Change Text Color',
	'bgcolor':'Change Background Color',
		'image':'Upload files',


      };