<?php return array (
  0 => 'uid,name,zhanghao,mima,ermima,email,shouji,weixin,weixinui,weibo,qqopen,zhifubaoopen,openid,openidd,jine,jifen,huobi,off,yanzhengip,touxiang,atime,ip,zhiye,xingbie,nianling,qqhaoma,weixinhaoma,tuid,tuid1,tuid2,adminid,level,appid,mhash',
  1 => 
  array (
    'uid' => 'auto_increment',
    'name' => 'name_',
    'zhanghao' => 'zhanghao_',
    'mima' => 'mima_',
    'ermima' => 'ermima_',
    'email' => 'email_',
    'shouji' => 'shouji_0',
    'weixin' => 'weixin_',
    'weixinui' => 'weixinui_',
    'weibo' => 'weibo_',
    'qqopen' => 'qqopen_',
    'zhifubaoopen' => 'zhifubaoopen_',
    'openid' => 'openid_',
    'openidd' => 'openidd_',
    'jine' => 'jine_0.00',
    'jifen' => 'jifen_0',
    'huobi' => 'huobi_0',
    'off' => 'off_0',
    'yanzhengip' => 'yanzhengip_0',
    'touxiang' => 'touxiang_',
    'atime' => 'atime_',
    'ip' => 'ip_',
    'zhiye' => 'zhiye_',
    'xingbie' => 'xingbie_-1',
    'nianling' => 'nianling_0',
    'qqhaoma' => 'qqhaoma_',
    'weixinhaoma' => 'weixinhaoma_',
    'tuid' => 'tuid_0',
    'tuid1' => 'tuid1_0',
    'tuid2' => 'tuid2_0',
    'adminid' => 'adminid_0',
    'level' => 'level_0',
    'appid' => 'appid_0',
    'mhash' => 'mhash_',
  ),
);